//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.hareketler = new HashSet<hareketler>();
        }
    
        public int per_id { get; set; }
        public string per_adsoyad { get; set; }
        public string per_kullaniciadi { get; set; }
        public string per_sifre { get; set; }
        public string per_mail { get; set; }
        public string per_sehir { get; set; }
        public string per_adres { get; set; }
        public string per_yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hareketler> hareketler { get; set; }
    }
}
