//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ucretlendırme
    {
        public int sure { get; set; }
        public Nullable<decimal> ucret { get; set; }
    }
}
